# Generated by Django 5.2.14 on 2026-05-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('filename', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('row_count_total', models.PositiveIntegerField(default=0)),
                ('row_count_success', models.PositiveIntegerField(default=0)),
                ('row_count_failed', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('scope_category', models.CharField(max_length=64)),
                ('activity_type', models.CharField(max_length=64)),
                ('activity_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('activity_unit', models.CharField(blank=True, max_length=32)),
                ('original_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=32)),
                ('facility_code', models.CharField(blank=True, max_length=64)),
                ('cost_center', models.CharField(blank=True, max_length=64)),
                ('vendor_id', models.CharField(blank=True, max_length=64)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('source_system', models.CharField(max_length=32)),
                ('source_record_id', models.CharField(blank=True, max_length=128)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('activity_based', 'Activity based'), ('spend_fallback', 'Spend fallback'), ('distance_estimated', 'Distance estimated')], max_length=32)),
                ('factor_source', models.CharField(max_length=255)),
                ('factor_value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('co2e_kg', models.DecimalField(decimal_places=6, max_digits=20)),
                ('co2e_tonnes', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emission_estimate', to='ingestion.normalizedactivity')),
            ],
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('batch', 'row_number')},
            },
        ),
        migrations.AddField(
            model_name='normalizedactivity',
            name='raw_row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_activity', to='ingestion.rawrow'),
        ),
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('plant_lookup', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_configs', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'source')},
            },
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['organization', 'review_status'], name='ingestion_n_organiz_30f639_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['organization', 'scope'], name='ingestion_n_organiz_a8661d_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['organization', 'batch'], name='ingestion_n_organiz_4f0ee8_idx'),
        ),
    ]
