# Generated by Django 5.2.14 on 2026-05-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='normalizedactivity',
            new_name='normalized__organiz_08a52b_idx',
            old_name='ingestion_n_organiz_30f639_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedactivity',
            new_name='normalized__organiz_53a005_idx',
            old_name='ingestion_n_organiz_a8661d_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedactivity',
            new_name='normalized__organiz_4266d2_idx',
            old_name='ingestion_n_organiz_4f0ee8_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs',
        ),
        migrations.AlterModelTable(
            name='datasourceconfig',
            table='data_source_configs',
        ),
        migrations.AlterModelTable(
            name='emissionestimate',
            table='emission_estimates',
        ),
        migrations.AlterModelTable(
            name='ingestionbatch',
            table='ingestion_batches',
        ),
        migrations.AlterModelTable(
            name='normalizedactivity',
            table='normalized_activities',
        ),
        migrations.AlterModelTable(
            name='rawrow',
            table='ingestion_raw_rows',
        ),
    ]
